name: NHL Manual Catchup or Debug
on:
  workflow_dispatch:
    inputs:
      sync_mode:
        description: 'Select Sync Mode'
        required: true
        default: 'catchup'
        type: choice
        options:
          - debug
          - catchup

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libomp-dev
        
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          
      - name: Run Sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: uv run sync_supabase.py ${{ github.event.inputs.sync_mode }}